spring:

  profiles:
    active: local

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true


  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    schema: classpath:db/hsqldb/schema.sql
    data: classpath:db/hsqldb/data.sql

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
     