DROP TABLE user IF EXISTS; 
create table user ( 
	id bigint generated by default as identity, 
	email varchar(255) not null, 
	name varchar(255) not null,
	create_date timestamp NULL DEFAULT current_timestamp(), 
	update_date timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
	primary key (id) 
) 
